// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: workload.proto
#ifndef GRPC_workload_2eproto__INCLUDED
#define GRPC_workload_2eproto__INCLUDED

#include "workload.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

class SpiffeWorkloadAPI final {
 public:
  static constexpr char const* service_full_name() {
    return "SpiffeWorkloadAPI";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // X.509-SVID Profile
    // Fetch all SPIFFE identities the workload is entitled to, as
    // well as related information like trust bundles and CRLs. As
    // this information changes, subsequent messages will be sent.
    std::unique_ptr< ::grpc::ClientReaderInterface< ::X509SVIDResponse>> FetchX509SVID(::grpc::ClientContext* context, const ::X509SVIDRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::X509SVIDResponse>>(FetchX509SVIDRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::X509SVIDResponse>> AsyncFetchX509SVID(::grpc::ClientContext* context, const ::X509SVIDRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::X509SVIDResponse>>(AsyncFetchX509SVIDRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::X509SVIDResponse>> PrepareAsyncFetchX509SVID(::grpc::ClientContext* context, const ::X509SVIDRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::X509SVIDResponse>>(PrepareAsyncFetchX509SVIDRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientReaderInterface< ::X509SVIDResponse>* FetchX509SVIDRaw(::grpc::ClientContext* context, const ::X509SVIDRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::X509SVIDResponse>* AsyncFetchX509SVIDRaw(::grpc::ClientContext* context, const ::X509SVIDRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::X509SVIDResponse>* PrepareAsyncFetchX509SVIDRaw(::grpc::ClientContext* context, const ::X509SVIDRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReader< ::X509SVIDResponse>> FetchX509SVID(::grpc::ClientContext* context, const ::X509SVIDRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::X509SVIDResponse>>(FetchX509SVIDRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::X509SVIDResponse>> AsyncFetchX509SVID(::grpc::ClientContext* context, const ::X509SVIDRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::X509SVIDResponse>>(AsyncFetchX509SVIDRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::X509SVIDResponse>> PrepareAsyncFetchX509SVID(::grpc::ClientContext* context, const ::X509SVIDRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::X509SVIDResponse>>(PrepareAsyncFetchX509SVIDRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientReader< ::X509SVIDResponse>* FetchX509SVIDRaw(::grpc::ClientContext* context, const ::X509SVIDRequest& request) override;
    ::grpc::ClientAsyncReader< ::X509SVIDResponse>* AsyncFetchX509SVIDRaw(::grpc::ClientContext* context, const ::X509SVIDRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::X509SVIDResponse>* PrepareAsyncFetchX509SVIDRaw(::grpc::ClientContext* context, const ::X509SVIDRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_FetchX509SVID_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // X.509-SVID Profile
    // Fetch all SPIFFE identities the workload is entitled to, as
    // well as related information like trust bundles and CRLs. As
    // this information changes, subsequent messages will be sent.
    virtual ::grpc::Status FetchX509SVID(::grpc::ServerContext* context, const ::X509SVIDRequest* request, ::grpc::ServerWriter< ::X509SVIDResponse>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_FetchX509SVID : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_FetchX509SVID() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_FetchX509SVID() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchX509SVID(::grpc::ServerContext* context, const ::X509SVIDRequest* request, ::grpc::ServerWriter< ::X509SVIDResponse>* writer) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFetchX509SVID(::grpc::ServerContext* context, ::X509SVIDRequest* request, ::grpc::ServerAsyncWriter< ::X509SVIDResponse>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_FetchX509SVID<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_FetchX509SVID : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_FetchX509SVID() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_FetchX509SVID() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FetchX509SVID(::grpc::ServerContext* context, const ::X509SVIDRequest* request, ::grpc::ServerWriter< ::X509SVIDResponse>* writer) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_FetchX509SVID : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithSplitStreamingMethod_FetchX509SVID() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler< ::X509SVIDRequest, ::X509SVIDResponse>(std::bind(&WithSplitStreamingMethod_FetchX509SVID<BaseClass>::StreamedFetchX509SVID, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithSplitStreamingMethod_FetchX509SVID() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FetchX509SVID(::grpc::ServerContext* context, const ::X509SVIDRequest* request, ::grpc::ServerWriter< ::X509SVIDResponse>* writer) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedFetchX509SVID(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::X509SVIDRequest,::X509SVIDResponse>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_FetchX509SVID<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_FetchX509SVID<Service > StreamedService;
};


#endif  // GRPC_workload_2eproto__INCLUDED
